.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DUMPLINGH" "1" "December 2018" "dumplingh developers" ""
.
.SH "NAME"
\fBdumplingh\fR \- Issue/PR exporter for GitHub
.
.SH "SYNOPSIS"
\fBdumplingh\fR \fIOPTIONS\fR \fIREPO_SLUG\fR
.
.SH "DESCRIPTION"
Issue/PR exporter for GitHub, which is a fancy name for dump issue and PR data to a JSON file\.
.
.P
Exit values and possible errors:
.
.IP "" 4
.
.nf

1 \- I/O error
2 \- parsing error
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
\fIREPO_SLUG\fR
.
.IP "" 4
.
.nf

Repository to export issues and PRs for in the form
"<username>/<repo>"\.
.
.fi
.
.IP "" 0
.
.P
\-i \-\-issues \fIISSUES_FILE\fR
.
.IP "" 4
.
.nf

File to export issues to\.

File must either not exist or \-\-force must be specified\.

Exclusive with \-\-no\-issues\.

Default: `\./<REPO_SLUG>\-issues\.json`\.
.
.fi
.
.IP "" 0
.
.P
\-p \-\-pulls \fIPULLS_FILE\fR
.
.IP "" 4
.
.nf

File to export pull requests to\.

File must either not exist or \-\-force must be specified\.

Exclusive with \-\-no\-pulls\.

Default: \./<REPO_SLUG>\-pulls\.json\.
.
.fi
.
.IP "" 0
.
.P
\-l \-\-labels \fILABELS_FILE\fR
.
.IP "" 4
.
.nf

File to export labels to\.

File must either not exist or \-\-force must be specified\.

Exclusive with \-\-no\-labels\.

Default: `\./<REPO_SLUG>\-labels\.json`\.
.
.fi
.
.IP "" 0
.
.P
\-m \-\-milestones \fIMILESTONES_FILE\fR
.
.IP "" 4
.
.nf

File to export milestones to\.

File must either not exist or \-\-force must be specified\.

Exclusive with \-\-no\-milestones\.

Default: `\./<REPO_SLUG>\-milestones\.json`\.
.
.fi
.
.IP "" 0
.
.P
\-\-projects \fIPROJECTS_FILE\fR
.
.IP "" 4
.
.nf

File to export projects to\.

File must either not exist or \-\-force must be specified\.

Exclusive with \-\-no\-projects\.

Requires \-\-auth, since GitHub fails on unauthorised requests to
experimental API endpoints\.

Default: `\./<REPO_SLUG>\-projects\.json`\.
.
.fi
.
.IP "" 0
.
.P
\-\-comments \fICOMMENTS_DIR\fR
.
.IP "" 4
.
.nf

Directory to export comments to\.

Directory must either not exist or \-\-force must be specified\.

Exclusive with \-\-no\-comments\.

Default: `\./<REPO_SLUG>\-comments`\.
.
.fi
.
.IP "" 0
.
.P
\-\-no\-issues
.
.IP "" 4
.
.nf

Don\'t export issues\.
.
.fi
.
.IP "" 0
.
.P
\-\-no\-pulls
.
.IP "" 4
.
.nf

Don\'t export pull requests\.
.
.fi
.
.IP "" 0
.
.P
\-\-no\-labels
.
.IP "" 4
.
.nf

Don\'t export labels\.
.
.fi
.
.IP "" 0
.
.P
\-\-no\-milestones
.
.IP "" 4
.
.nf

Don\'t export milestones\.
.
.fi
.
.IP "" 0
.
.P
\-\-no\-projects
.
.IP "" 4
.
.nf

Don\'t export projects\.
.
.fi
.
.IP "" 0
.
.P
\-\-no\-comments
.
.IP "" 4
.
.nf

Don\'t export comments\.
.
.fi
.
.IP "" 0
.
.P
\-f \-\-force
.
.IP "" 4
.
.nf

Allow for overriding <ISSUES_FILE> and <PULLS_FILE>\.
.
.fi
.
.IP "" 0
.
.P
\-c \-\-compact
.
.IP "" 4
.
.nf

Compact\-print, rather than pretty\-print the exported issues/pull requests\.
.
.fi
.
.IP "" 0
.
.P
\-a \-\-auth [OAUTH2_TOKEN]
.
.IP "" 4
.
.nf

Token to authenticate to GitHub with\.

Recommended for more requests\.

Required for \-\-projects\.
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.P
Instigated by Vendethiel <\fIhttps://github\.com/vendethiel\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/dumplingh/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/dumplingh\fR>
